# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b5d9a818997881c7a0a5a665b0f5e9865f49e13f14d89a546cf8b86db196f19b6016dcce3e270984108aae1dcef59c8e4150bcbf5d3a306f7ac38acd6947c30

test:
  secret_key_base: f2d3a3c883a24996af0f541d1268ecb0f180ae496d3535e735133970845d8c5f62dc4a11ef44099200508e8387ec98cbc6f6b3cf6091ed881c39465a30b06158

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
